spring.application.name=CTMSS
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.output.ansi.enabled=ALWAYS
logging.level.root=INFO
logging.level.org.personal.ctmss=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.flywaydb=INFO
security.jwt.secret-key=cAU7wjlkcPdcJ5CODLTGq+Yd9gpYRwK0VsIGstaupkM=
spring.datasource.url=jdbc:postgresql://localhost:5432/CTMS
spring.datasource.username=postgres
spring.datasource.password=Murtaza@786